import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import BeautifulNavbar from "./components/BeautifulNavbar";
import SessionProviderClient from "./providers/SessionProviderClient";
import DevServiceWorkerCleanup from "./components/DevServiceWorkerCleanup";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import LayoutShell from "./components/LayoutShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo_original.png",
    shortcut: "/logo_original.png",
    apple: "/logo_original.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/logo_original.png" />
        <link rel="shortcut icon" href="/logo_original.png" />
        <link rel="apple-touch-icon" href="/logo_original.png" />
        {process.env.NODE_ENV !== 'production' ? (
          // Inline script runs as early as possible to mute noisy Workbox/_rsc logs
          <script
            dangerouslySetInnerHTML={{
              __html: `(() => {
  try {
    const FILTER_RE = /workbox|_rsc=|workbox-\w+/i;
    ['log','info','warn','error','debug'].forEach((m) => {
      const orig = console[m];
      console[m] = function(...args){
        try { if (args.length && typeof args[0] === 'string' && FILTER_RE.test(args[0])) return; } catch(e){}
        return orig.apply(console, args);
      };
    });
  } catch(e){}
})();`,
            }}
          />
        ) : null}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderClient>
          {process.env.NODE_ENV !== 'production' && <DevServiceWorkerCleanup />}
          <LayoutShell>{children}</LayoutShell>
          <ToastContainer position="top-right" />
        </SessionProviderClient>
      </body>
    </html>
  );
}
